ServerName      "ProFTPD"
ServerType      standalone
DefaultServer   on

Port            21
Umask           022
MaxInstances    30

User            nobody
Group           nogroup

DefaultRoot     /var/www/html

<Directory /var/www/html/*>
  AllowOverwrite on
</Directory>

<Limit SITE_CHMOD>
  DenyAll
</Limit>

RequireValidShell off
UseFtpUsers off

PassivePorts    21000 21010
